# Dockerfile.dev

FROM node:14-alpine

WORKDIR /app

RUN npm i -g @nestjs/cli

# COPY package*.json ./

# RUN npm install

# COPY 

EXPOSE 3000

# CMD ["npm", "start"]

#임시
CMD ["ash", "-c", "while true; do sleep 1; done"]